# Generated by Django 6.1 on 2026-08-17 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jamaah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer', models.CharField(choices=[('fajr', 'Fajr'), ('dhuhr', 'Dhuhr'), ('asr', 'Asr'), ('maghrib', 'Maghrib'), ('isha', 'Isha'), ('jumuah', "Jumu'ah")], max_length=20)),
                ('location_type', models.CharField(choices=[('current', 'Current location'), ('selected', 'Selected location'), ('public', 'Public place'), ('workplace', 'Workplace'), ('university', 'University'), ('park', 'Park'), ('other', 'Other')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address_label', models.CharField(blank=True, max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jamaahs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jamaah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='jamaah.jamaah')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('jamaah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='jamaah.jamaah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jamaah_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='jamaah',
            index=models.Index(fields=['status'], name='jamaah_jama_status_7e46b5_idx'),
        ),
        migrations.AddIndex(
            model_name='jamaah',
            index=models.Index(fields=['scheduled_at'], name='jamaah_jama_schedul_71edaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.UniqueConstraint(fields=('jamaah', 'requester'), name='unique_jamaah_requester'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('jamaah', 'user'), name='unique_jamaah_member'),
        ),
    ]
