# Generated by Django 6.1 on 2026-08-17 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamaah', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer', models.CharField(choices=[('fajr', 'Fajr'), ('dhuhr', 'Dhuhr'), ('asr', 'Asr'), ('maghrib', 'Maghrib'), ('isha', 'Isha'), ('jumuah', "Jumu'ah")], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_miles', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pray_needs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='jamaah_pray_status_a3ec29_idx')],
            },
        ),
    ]
